#!/usr/bin/env python3
"""
Backfill image_urls for exercises that are missing them.

Downloads the free-exercise-db exercises.json, matches by exercise name,
and generates a SQL UPDATE script to populate image_urls.

Usage:
  python scripts/backfill_image_urls.py
  # Then run the output SQL: supabase/seed/backfill_images.sql
"""

import json
import urllib.request
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent
REPO_ROOT = SCRIPT_DIR.parent
CACHE_DIR = SCRIPT_DIR / ".cache"
CACHE_FILE = CACHE_DIR / "exercises.json"
OUTPUT_FILE = REPO_ROOT / "supabase" / "seed" / "backfill_images.sql"

EXERCISES_URL = "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/dist/exercises.json"
IMAGES_BASE_URL = (
    "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/"
)


def sql_string(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"


def sql_array(items: list[str]) -> str:
    if not items:
        return "NULL"
    escaped = [sql_string(i) for i in items]
    return f"ARRAY[{', '.join(escaped)}]"


def main():
    CACHE_DIR.mkdir(parents=True, exist_ok=True)

    if CACHE_FILE.exists():
        print(f"Using cached: {CACHE_FILE}")
    else:
        print(f"Downloading from {EXERCISES_URL}...")
        urllib.request.urlretrieve(EXERCISES_URL, CACHE_FILE)

    with open(CACHE_FILE, "r", encoding="utf-8") as f:
        data = json.load(f)

    print(f"Loaded {len(data)} exercises")

    lines = [
        "-- Backfill image_urls for exercises from free-exercise-db",
        "-- Generated by scripts/backfill_image_urls.py",
        "-- Run with: psql or supabase db execute",
        "",
    ]

    count = 0
    for ex in data:
        name = ex.get("name", "").strip()
        images = ex.get("images") or []
        if not name or not images:
            continue

        image_urls = [f"{IMAGES_BASE_URL}{img}" for img in images]
        lines.append(
            f"UPDATE exercises SET image_urls = {sql_array(image_urls)} "
            f"WHERE name = {sql_string(name)} AND (image_urls IS NULL OR image_urls = '{{}}');"
        )
        count += 1

    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"Generated {count} UPDATE statements → {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
